feat/extract_speech
OpenVoiceOS/ovos-plugin-manager pull request #139
Opened 2023-04-09 19:26 UTC by JarbasAl

add support for VAD plugins to return only the speech from a audio chunk

2023-04-10 00:19 UTC, emphasize commented on ovos_plugin_manager/templates/vad.py
> +
dont need `duration` here ( duration = self.frame_duration_ms / 1000.0)
But its late, am i wrong?

2023-04-19 23:07 UTC, NeonDaniel requested changes

2023-04-19 23:07 UTC, NeonDaniel commented on ovos_plugin_manager/templates/vad.py
> +    def __init__(self, bytes, timestamp, duration):
Please add type annotations and docstrings to specify expected arg values

2023-04-19 23:07 UTC, NeonDaniel commented on ovos_plugin_manager/templates/vad.py
> +    def frame_generator(self, audio):
Please add type annotation and/or update docstring to describe `audio`

2023-04-19 23:07 UTC, NeonDaniel commented on ovos_plugin_manager/templates/vad.py
> +    def extract_speech(self, audio):
Please add type annotation and/or update docstring to describe audio

2023-09-08 18:05 UTC, merged