Feat/ui helper
OpenVoiceOS/ovos-plugin-manager pull request #85
Opened 2022-10-22 17:43 UTC by JarbasAl

add a new class for consumption by downstream appstore like integrations

This new class is the central place to manage anything UI related,  downstream should not need to import anything else
    
This allows all sorts of rich integrations by any downstream application, terminal, web, GUI...
    
initial implementation only for stt and tts, extracted from setup skill. future PRs will add other kinds of plugins

a companion PR in setup skill should be made after this is merged, the logic is a drop in replacement but imports and requirements need to be updated

2022-10-22 17:45 UTC, JarbasAl commented on ovos_plugin_manager/utils/ui.py
> +        engine = cfg["engine"]
TODO - i dont think "engine" is always present, verify the other helper methods to ensure it is

2022-10-22 19:38 UTC, JarbasAl commented
images of what a UI using this "extra_setup" could look like

![](https://user-images.githubusercontent.com/19663666/93578156-99ee8380-f9ba-11ea-846f-25fa45abc0e8.png)
![](https://user-images.githubusercontent.com/19663666/93578328-d0c49980-f9ba-11ea-9d93-a8dd8476a0ab.png)

2022-10-23 00:10 UTC, AIIX requested changes

2022-10-23 00:25 UTC, AIIX commented
Not sure how this skill settings GUI will help with completely, I thought this was to allow plugins to pre decide and provide a gui specific config coming directly from the plugins that can for example state i have modules and voices vs plugins that state i have only voices for the setup skill GUI list or moving it into a more cleaner nested GUI list, For plugins that provide configs it seems to make sense to have this skill setting GUI applied to them for user facing changes, but i think the pre defined gui config was something very internal to gui building and not user facing

2022-10-23 02:34 UTC, AIIX commented
I have seem to have better solution to the list problem so maybe i don't need to care weather a plugin supports modules or not  anymore gui side this seems much cleaner:
 
![a-better-tts-selection-menu](https://user-images.githubusercontent.com/19663666/197370339-c99ce588-f0f4-4bfd-ad1c-ecfacaac89f7.gif)

2022-10-23 04:11 UTC, JarbasAl commented on ovos_plugin_manager/utils/ui.py
> +        opt = {"plugin_name": plugin_display_name,
what are you going on about again with "the issue where the API should be sending always the same key entries for all modules", open an issue with a proper bug report if thats the case? 

even before this PR the gui was always sent the same keys, with this PR the gui keeps getting the same keys but it has been further standardized to help in consistency and future updates, but nothing changed in regards to the data mycroft-gui will see

2022-10-23 04:14 UTC, JarbasAl commented
> Not sure how this skill settings GUI will help with completely, I thought this was to allow plugins to pre decide and provide a gui specific config coming directly from the plugins that can for example state i have modules and voices vs plugins that state i have only voices for the setup skill GUI list or moving it into a more cleaner nested GUI list, For plugins that provide configs it seems to make sense to have this skill setting GUI applied to them for user facing changes, but i think the pre defined gui config was something very internal to gui building and not user facing

as explained several times, this is for a NEW page, for plugins such as polly TTS that require credentials in order to work. it was even you who suggested i called it "extra_setup" in the chat

for the nested list view i did not add anything because that is not yet supported, if you implement it gui side i can add that, as i said i can add any new keys you need

2022-10-23 05:45 UTC, JarbasAl commented
here is how a plugin would provide the metadata for the extra setup page described above https://github.com/OpenVoiceOS/ovos-tts-plugin-polly/blob/dev/ovos_tts_plugin_polly/__init__.py#L235

2022-10-23 05:49 UTC, AIIX commented
> here is how a plugin would provide the metadata for the extra setup page described above https://github.com/OpenVoiceOS/ovos-tts-plugin-polly/blob/dev/ovos_tts_plugin_polly/__init__.py#L235

```
        s = {"key_id": "", 
              "secret_key": "", 
              "region": "us-east-1"}
```
Is this what the fields need to be generated for ?

2022-10-23 05:52 UTC, JarbasAl commented
> > here is how a plugin would provide the metadata for the extra setup page described above https://github.com/OpenVoiceOS/ovos-tts-plugin-polly/blob/dev/ovos_tts_plugin_polly/__init__.py#L235
> 
> ```
>         s = {"key_id": "", 
>               "secret_key": "", 
>               "region": "us-east-1"}
> ```
> 
> Is this what the fields need to be generated for ?

for this specific plugin yes, but it could be anything at all that the plugin needs, just like skill settings can be anything the individual skill needs

i suppose some plugins may need quite advanced setups, but the most common case will likely be a couple strings entries for api keys

also note this applies to every plugin supported by OPM, not only TTS and STT, the aim is to have a universal interface for this across all ovos projects

2022-10-23 06:17 UTC, AIIX commented
> > > here is how a plugin would provide the metadata for the extra setup page described above https://github.com/OpenVoiceOS/ovos-tts-plugin-polly/blob/dev/ovos_tts_plugin_polly/__init__.py#L235
> > 
> > ```
> >         s = {"key_id": "", 
> >               "secret_key": "", 
> >               "region": "us-east-1"}
> > ```
> > 
> > Is this what the fields need to be generated for ?
> 
> for this specific plugin yes, but it could be anything at all that the plugin needs, just like skill settings can be anything the individual skill needs
> 
> i suppose some plugins may need quite advanced setups, but the most common case will likely be a couple strings entries for api keys
> 
> also note this applies to every plugin supported by OPM, not only TTS and STT, the aim is to have a universal interface for this across all ovos projects

apart from setup skill where all does this ui interface need to be displayed ? That determines where the ui generator fields page and field templates pages should live

2022-10-23 18:13 UTC, JarbasAl commented
> > > > here is how a plugin would provide the metadata for the extra setup page described above https://github.com/OpenVoiceOS/ovos-tts-plugin-polly/blob/dev/ovos_tts_plugin_polly/__init__.py#L235
> > > 
> > > 
> > > ```
> > >         s = {"key_id": "", 
> > >               "secret_key": "", 
> > >               "region": "us-east-1"}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Is this what the fields need to be generated for ?
> > 
> > 
> > for this specific plugin yes, but it could be anything at all that the plugin needs, just like skill settings can be anything the individual skill needs
> > i suppose some plugins may need quite advanced setups, but the most common case will likely be a couple strings entries for api keys
> > also note this applies to every plugin supported by OPM, not only TTS and STT, the aim is to have a universal interface for this across all ovos projects
> 
> apart from setup skill where all does this ui interface need to be displayed ? That determines where the ui generator fields page and field templates pages should live

open question, but my initial inclination is that it should be a PHAL plugin serving any random downstream consumers

any component with a settings page could register with its skill_id and be available via bus api provided by the PHAL plugin, any GUI or terminal app could then use the bus to get a dict of skill_id: settings meta

the display itself is more tricky, the basic usage would have the plugin itself use the GUIInterface class, but setups like ovos-shell could handle this directly and just tell the plugin to not display if configured as such.

i think this plugin could provide a native mycroft.conf setup also and perhaps replace the configuration provider plugin, ie, migrate that plugin to use the universal settingsmeta scheme

2022-10-23 23:41 UTC, AIIX commented
> > > > > here is how a plugin would provide the metadata for the extra setup page described above https://github.com/OpenVoiceOS/ovos-tts-plugin-polly/blob/dev/ovos_tts_plugin_polly/__init__.py#L235
> > > > 
> > > > 
> > > > ```
> > > >         s = {"key_id": "", 
> > > >               "secret_key": "", 
> > > >               "region": "us-east-1"}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Is this what the fields need to be generated for ?
> > > 
> > > 
> > > for this specific plugin yes, but it could be anything at all that the plugin needs, just like skill settings can be anything the individual skill needs
> > > i suppose some plugins may need quite advanced setups, but the most common case will likely be a couple strings entries for api keys
> > > also note this applies to every plugin supported by OPM, not only TTS and STT, the aim is to have a universal interface for this across all ovos projects
> > 
> > 
> > apart from setup skill where all does this ui interface need to be displayed ? That determines where the ui generator fields page and field templates pages should live
> 
> open question, but my initial inclination is that it should be a PHAL plugin serving any random downstream consumers
> 
> any component with a settings page could register with its skill_id and be available via bus api provided by the PHAL plugin, any GUI or terminal app could then use the bus to get a dict of skill_id: settings meta
> 
> the display itself is more tricky, the basic usage would have the plugin itself use the GUIInterface class, but things like ovos-shell and setup skill could handle this directly and just tell the plugin to not display if configured as such. like factory reset basically
> 
> i think this plugin could provide a native mycroft.conf setup also and perhaps replace the configuration provider plugin, ie, migrate that plugin to use the universal settingsmeta scheme

The configuration provider PHAL plugin already provides a similar interface for mycroft.conf, so would prefer to have this interface coming from there itself, as it already also includes most of the field building templates needed for this type of UI interface

2022-10-23 23:47 UTC, JarbasAl commented
yes thats what i meant, sorry if it wasnt clear

i meant making the existing configuration provider plugin accept a settingsmeta structure from the bus, this will work for skills or even external apps

but i also think mycroft.conf itself should use settingsmeta.json structure

2022-10-24 14:33 UTC, AIIX approved these changes

2022-10-24 15:00 UTC, merged